# Generated by Django 4.2.5 on 2023-09-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0002_alter_recommendation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'permissions': [('can_view_recommendation', 'Can view recommendation'), ('can_delete_recommendation', 'Can delete recommendation')]},
        ),
    ]
