# Generated by Django 4.2.5 on 2023-09-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0003_alter_recommendation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={},
        ),
    ]
