# Generated by Django 4.2.5 on 2023-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0004_alter_recommendation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
            ],
        ),
    ]
