# Generated by Django 4.2.5 on 2023-09-27 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0005_typesupport_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='support',
            old_name='type_support',
            new_name='id_type_support',
        ),
        migrations.CreateModel(
            name='EducationalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('web_site', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('id_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_crafters_api.support')),
                ('id_type_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_crafters_api.typeinstitute')),
            ],
        ),
    ]
