# Generated by Django 4.2.5 on 2023-09-27 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0005_typesupport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
                ('type_support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_crafters_api.typesupport')),
            ],
        ),
    ]
