# Generated by Django 4.2.5 on 2023-09-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0006_typeinstitute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationalinstitution',
            name='location',
            field=models.CharField(default='Colombia', max_length=150),
        ),
    ]
