# Generated by Django 4.2.5 on 2023-09-27 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0006_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='url',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
