# Generated by Django 4.2.5 on 2023-09-28 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0008_remove_educationalinstitution_id_support_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupportEducationalInstitution',
            new_name='SupportForEducationalInstitution',
        ),
    ]
