# Generated by Django 4.2.5 on 2023-09-28 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0009_rename_supporteducationalinstitution_supportforeducationalinstitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='requirements',
        ),
        migrations.AddField(
            model_name='support',
            name='id_educational_institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='code_crafters_api.educationalinstitution'),
        ),
    ]
