# Generated by Django 4.2.5 on 2023-09-28 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_crafters_api', '0010_remove_support_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='requirements',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='support',
            name='id_type_support',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='code_crafters_api.typesupport'),
        ),
    ]
